# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=225)),
                ('firstName', models.CharField(max_length=225)),
                ('secondName', models.CharField(max_length=225)),
            ],
        ),
    ]
