# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 06:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20160610_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(b'^\\d+$', b'Only numbers are allowed.'), django.core.validators.MaxLengthValidator])),
                ('email', models.EmailField(max_length=254, verbose_name=b'email')),
                ('visitingPerson', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
