# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 00:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160610_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2016, 6, 9)),
            preserve_default=False,
        ),
    ]
