# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_visitor_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
