# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20160611_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='created_date',
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
